### ISSUE TITLE
Error when installing on Docker 

### ISSUE THREAD

**Issue by SirZazu** [madisona/django-google-maps#35]
Hello,
I have spotted that `django-google-maps` have a problem to properly install under Docker container. 

I am using `python:3.6-alpine` official image and installing requirements from pip finish with a traceback:

```
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-etjs66mk/django-google-maps/setup.py", line 38, in <module>
      zip_safe=False,
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 257, in run
      self.distinfo_dir)
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 427, in egg2dist
      distribution=self.distribution)
    File "/usr/local/lib/python3.6/site-packages/wheel/metadata.py", line 177, in pkginfo_to_dict
      new_requirements = sorted(convert_requirements(requirements))
    File "/usr/local/lib/python3.6/site-packages/wheel/metadata.py", line 234, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3047, in parse
      req, = parse_requirements(s)
  ValueError: not enough values to unpack (expected 1, got 0)
```
I have checked version `0.6.0` and `0.10.0`. I did update of `setuptools, pip, wheel` but with no luck.
Probably related tightly to Alpine Linux distribution. Any advice how to fix it?

**EDIT:** After some debugging I have found out that the package is correctly installed tho and exists in `site-packages`

```
pip freeze | grep 'google'
django-google-maps==0.10.0
```
I am super confused now. But seems that this error during installation is not affecting the process.

**Comment by madisona** [comment]
@SirZazu this has been published as version `0.10.1`
